import os
import sqlite3
import logging
from pathlib import Path

logger = logging.getLogger(__name__)

# Desacoplamiento estructural mediante variable de entorno con fallback dinámico
APP_ROOT = os.getenv("APP_ROOT")
if APP_ROOT:
    BASE_DIR = Path(APP_ROOT).resolve()
else:
    BASE_DIR = Path(__file__).resolve().parents[2]

def _to_absolute_path(env_var: str, default_rel: str) -> str:
    """Garantiza la resolución de un path absoluto basándose en APP_ROOT o la raíz calculada."""
    raw_path = os.getenv(env_var, default_rel)
    p = Path(raw_path)
    if not p.is_absolute():
        p = BASE_DIR / p
    return str(p.resolve())

def _attach_fsm_database(conn: sqlite3.Connection) -> None:
    """
    Capability Bootstrap: Enlaza el esquema FSM de forma permanente al contexto de la conexión.
    Aísla la lógica CQRS cruzada para simplificar testing unitario y migraciones.
    """
    fsm_db_path = _to_absolute_path("FSM_DB_PATH", "infra/db/fsm.db")
    
    if os.path.exists(fsm_db_path):
        attached = conn.execute("PRAGMA database_list").fetchall()
        if not any(db[1] == "fsm_db" for db in attached):
            try:
                # Sanitización de literales para prevenir inyecciones de path en ATTACH
                safe_fsm_path = fsm_db_path.replace("'", "''")
                conn.execute(f"ATTACH DATABASE '{safe_fsm_path}' AS fsm_db")
                logger.debug(f"Volumen CQRS acoplado exitosamente: {safe_fsm_path}")
            except sqlite3.OperationalError as e:
                logger.error(f"CRÍTICO: Fallo al enlazar (ATTACH) FSM DB {fsm_db_path}: {e}")
                conn.close()
                raise
    else:
        logger.warning(f"ATTACH diferido: El archivo maestro {fsm_db_path} no se encuentra en el disco.")

def get_connection(db_path: str, timeout: int = 15) -> sqlite3.Connection:
    """
    CRITICAL ARCHITECTURAL CONSTRAINT:
    Connections generated by this factory are STRICTLY THREAD-CONFINED.
    pysqlite isolation relies on check_same_thread=True (default) to catch misuse early.
    """
    # SOTA Bypass: Preservar el comportamiento transient nativo para pruebas unitarias en RAM
    if db_path == ":memory:":
        abs_db_path = ":memory:"
    else:
        p_db = Path(db_path)
        abs_db_path = str(p_db.resolve()) if p_db.is_absolute() else str((BASE_DIR / p_db).resolve())
    
    conn = sqlite3.connect(abs_db_path, timeout=timeout)
    conn.execute("PRAGMA journal_mode=WAL")
    conn.execute("PRAGMA synchronous=NORMAL")
    conn.execute(f"PRAGMA busy_timeout={timeout * 1000}")
    
    # Determinismo Estricto: Validación por nombre de archivo base
    target_queue_name = Path(_to_absolute_path("QUEUE_DB_PATH", "infra/db/queue.db")).name
    if Path(abs_db_path).name == target_queue_name:
        _attach_fsm_database(conn)

    return conn